import img158100 from '@/assets/images/saveImg/intelligentInfo/158100.webp'
import img158101 from '@/assets/images/saveImg/intelligentInfo/158101.webp'
import img158102 from '@/assets/images/saveImg/intelligentInfo/158102.webp'
import img25213_1 from '@/assets/images/saveImg/intelligentInfo/25213_1.png'
import img25213_2 from '@/assets/images/saveImg/intelligentInfo/25213_2.png'
import img32035 from '@/assets/images/saveImg/intelligentInfo/32035.png'
import img40018 from '@/assets/images/saveImg/intelligentInfo/40018.png'
import img32034 from '@/assets/images/saveImg/intelligentInfo/32034.png'
import img36196 from '@/assets/images/saveImg/intelligentInfo/36196.png'
import img17905 from '@/assets/images/saveImg/intelligentInfo/17905.png'
import img14733 from '@/assets/images/saveImg/intelligentInfo/14733.png'
import img14734 from '@/assets/images/saveImg/intelligentInfo/14734.png'
import img14735 from '@/assets/images/saveImg/intelligentInfo/14735.png'
import img32027 from '@/assets/images/saveImg/intelligentInfo/32027.png'
import img32029 from '@/assets/images/saveImg/intelligentInfo/32029.png'
import img25214_1 from '@/assets/images/saveImg/intelligentInfo/25214_1.png'
import img25214_2 from '@/assets/images/saveImg/intelligentInfo/25214_2.jpg'
import img41012 from '@/assets/images/saveImg/intelligentInfo/41012.png'
import img32039 from '@/assets/images/saveImg/intelligentInfo/32039.png'
import img41013 from '@/assets/images/saveImg/intelligentInfo/41013.png'
import img32041 from '@/assets/images/saveImg/intelligentInfo/32041.png'
import img14742 from '@/assets/images/saveImg/intelligentInfo/14742.png'
import img14744 from '@/assets/images/saveImg/intelligentInfo/14744.png'
import img32043 from '@/assets/images/saveImg/intelligentInfo/32043.png'
import img31743 from '@/assets/images/saveImg/intelligentInfo/31743.png'
import img41756 from '@/assets/images/saveImg/intelligentInfo/41756.png'
import img14743 from '@/assets/images/saveImg/intelligentInfo/14743.png'
import img41757 from '@/assets/images/saveImg/intelligentInfo/41757.png'
import img2526_1 from '@/assets/images/saveImg/intelligentInfo/2526_1.png'
import img2526_2 from '@/assets/images/saveImg/intelligentInfo/2526_2.png'
import img41938 from '@/assets/images/saveImg/intelligentInfo/41938.png'
import img41939 from '@/assets/images/saveImg/intelligentInfo/41939.png'
import img41940 from '@/assets/images/saveImg/intelligentInfo/41940.png'
import img41941 from '@/assets/images/saveImg/intelligentInfo/41941.png'
import img41942 from '@/assets/images/saveImg/intelligentInfo/41942.png'
import img41943 from '@/assets/images/saveImg/intelligentInfo/41943.png'
import img41944 from '@/assets/images/saveImg/intelligentInfo/41944.png'
import img41945 from '@/assets/images/saveImg/intelligentInfo/41945.png'
import img41946 from '@/assets/images/saveImg/intelligentInfo/41946.png'
import img2527_1 from '@/assets/images/saveImg/intelligentInfo/2527_1.png'
import img2527_2 from '@/assets/images/saveImg/intelligentInfo/2527_2.png'
import img41977 from '@/assets/images/saveImg/intelligentInfo/41977.png'
import img41978 from '@/assets/images/saveImg/intelligentInfo/41978.png'
import img41979 from '@/assets/images/saveImg/intelligentInfo/41979.png'
import img41980 from '@/assets/images/saveImg/intelligentInfo/41980.png'
import img41981 from '@/assets/images/saveImg/intelligentInfo/41981.png'
import img41982 from '@/assets/images/saveImg/intelligentInfo/41982.png'
import img41983 from '@/assets/images/saveImg/intelligentInfo/41983.png'
import img41984 from '@/assets/images/saveImg/intelligentInfo/41984.png'
import img41985 from '@/assets/images/saveImg/intelligentInfo/41985.png'
import img2528_1 from '@/assets/images/saveImg/intelligentInfo/2528_1.png'
import img2529_1 from '@/assets/images/saveImg/intelligentInfo/2529_1.png'
import img2530_1 from '@/assets/images/saveImg/intelligentInfo/2530_1.png'

// http://codercba.com:9060/oppo-nuxt/api/home/info?type=intelligent
export default {
  code: 200,
  data: {
    navbars: [
      {
        id: '1276',
        title: 'OPPO专区',
        type: 'oppo',
        showName: 0,
        url: '',
        jsonUrl: '',
        clickUrl: '',
        jsonClickUrl: '',
        beginAt: null,
        endAt: null,
        seq: 100,
        labelDetailss: [],
        link: 'https://www.opposhop.cn/cn/web/topic/700100.html',
        isLogin: 0,
        moduleCode: '700002',
        rows: 0,
        cols: 0,
        maxProductNum: 0
      },
      {
        id: '1277',
        title: 'OnePlus专区',
        type: 'onePlus',
        showName: 0,
        url: '',
        jsonUrl: '',
        clickUrl: '',
        jsonClickUrl: '',
        beginAt: null,
        endAt: null,
        seq: 90,
        labelDetailss: [],
        link: 'https://www.opposhop.cn/cn/web/topic/700200.html',
        isLogin: 0,
        moduleCode: '700002',
        rows: 0,
        cols: 0,
        maxProductNum: 0
      },
      {
        id: '1280',
        title: '智能硬件',
        type: 'intelligent',
        showName: 0,
        url: '',
        jsonUrl: '',
        clickUrl: '',
        jsonClickUrl: '',
        beginAt: null,
        endAt: null,
        seq: 75,
        labelDetailss: [],
        link: 'https://www.opposhop.cn/cn/web/topic/700400.html',
        isLogin: 0,
        moduleCode: '700002',
        rows: 0,
        cols: 0,
        maxProductNum: 0
      },
      {
        id: '1281',
        title: '服务',
        type: 'server',
        showName: 0,
        url: '',
        jsonUrl: '',
        clickUrl: '',
        jsonClickUrl: '',
        beginAt: null,
        endAt: null,
        seq: 50,
        labelDetailss: [],
        link: 'https://support.oppo.com/cn/',
        isLogin: 0,
        moduleCode: '700002',
        rows: 0,
        cols: 0,
        maxProductNum: 0
      }
    ],
    banners: [
      {
        id: 158100,
        picStr: img158100,
        link: 'https://www.opposhop.cn/cn/web/products/8384.html'
      },
      {
        id: 158101,
        picStr: img158101,
        link: 'https://www.opposhop.cn/cn/web/products/20585.html'
      },
      {
        id: 158102,
        picStr: img158102,
        link: 'https://www.opposhop.cn/cn/web/products/8884.html'
      }
    ],
    categorys: [
      {
        id: 25213,
        picStr: img25213_1,
        url: img25213_2,
        title: '智能声学',
        moduleCode: '701101',
        productDetailss: [
          {
            id: '32035',
            skuId: 8412,
            title: 'OPPO Enco Air2i 真无线耳机 曜石黑',
            secondTitle: '10mm 超大动圈',
            thirdTitle: '',
            url: img32035,
            jsonUrl: '',
            video: '',
            seq: 1200,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6806,
            goodsSpuName: 'OPPO Enco Air2i 真无线耳机',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '149',
              marketPrice: '',
              buyPrice: '118',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 118,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/8412.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 5,
                activityInfo: '积分抵5元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco Air2i 真无线耳机 曜石黑',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '40018',
            skuId: 6711,
            title: 'OPPO Enco Air2 Pro',
            secondTitle: 'ANC 主动降噪',
            thirdTitle: '',
            url: img40018,
            jsonUrl: '',
            video: '',
            seq: 1180,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6196,
            goodsSpuName: 'OPPO Enco Air2 Pro',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '299',
              marketPrice: '',
              buyPrice: '218',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 218,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/6711.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 5,
                activityInfo: '积分抵5%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco Air2 Pro 月牙白',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '32034',
            skuId: 7480,
            title: 'OPPO Enco X2 旗舰新品真无线降噪耳机 凝霜白 有线充版',
            secondTitle: '45dB 降噪深度',
            thirdTitle: '',
            url: img32034,
            jsonUrl: '',
            video: '',
            seq: 1150,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 21452,
            goodsSpuName: 'OPPO Enco X2',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '899',
              marketPrice: '',
              buyPrice: '789',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 789,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/7480.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '6期免息'
              },
              {
                type: 3,
                activityInfo: '满49减10'
              },
              {
                type: 5,
                activityInfo: '积分抵5%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco X2 凝霜白 有线充版',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '36196',
            skuId: 22705,
            title: 'OPPO Enco Air2 新品真无线蓝牙耳机 晨雾白',
            secondTitle: '3.5 g 超轻无感',
            thirdTitle: '',
            url: img36196,
            jsonUrl: '',
            video: '',
            seq: 1100,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 21374,
            goodsSpuName: 'OPPO Enco Air2',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '199',
              marketPrice: '',
              buyPrice: '148',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 148,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/22705.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 5,
                activityInfo: '积分抵10元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco Air2 晨雾白',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '17905',
            skuId: 22136,
            title: 'OPPO Enco Free2i',
            secondTitle: '42dB 降噪深度',
            thirdTitle: '',
            url: img17905,
            jsonUrl: '',
            video: '',
            seq: 1100,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 21143,
            goodsSpuName: 'OPPO Enco Free2i',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '399',
              marketPrice: '',
              buyPrice: '319',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 319,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/22136.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满49减10'
              },
              {
                type: 5,
                activityInfo: '积分抵10%'
              }
            ],
            placeholderLabel: {
              type: 20,
              activityInfo: '缺货'
            },
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco Free2i 真无线蓝牙降噪耳机 浮云白',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14733',
            skuId: 4253,
            title: 'OPPO Enco Air 灵动版',
            secondTitle: '24小时超长续航',
            thirdTitle: '',
            url: img14733,
            jsonUrl: '',
            video: '',
            seq: 1000,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1720,
            goodsSpuName: 'OPPO Enco Air 灵动版',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '199',
              marketPrice: '',
              buyPrice: '98',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 98,
            originalPrice: 199,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/4022.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 5,
                activityInfo: '积分抵5%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco Air 灵动版 纯白',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14734',
            skuId: 3501,
            title: 'OPPO Enco X 降噪耳机',
            secondTitle: '双重主动降噪',
            thirdTitle: '',
            url: img14734,
            jsonUrl: '',
            video: '',
            seq: 900,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 973,
            goodsSpuName: 'OPPO Enco X',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '999',
              marketPrice: '',
              buyPrice: '489',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 489,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/3501.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '6期免息'
              },
              {
                type: 3,
                activityInfo: '满49减10'
              },
              {
                type: 5,
                activityInfo: '积分抵10%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco X 蓝调',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14735',
            skuId: 20585,
            title: 'OPPO Enco Air 灵动版',
            secondTitle: '24小时超长续航',
            thirdTitle: '',
            url: img14735,
            jsonUrl: '',
            video: '',
            seq: 800,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1720,
            goodsSpuName: 'OPPO Enco Air 灵动版',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '199',
              marketPrice: '',
              buyPrice: '98',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 98,
            originalPrice: 199,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/20585.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 5,
                activityInfo: '积分抵5%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco Air 灵动版 淡蓝',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '32027',
            skuId: 4522,
            title: 'OPPO Enco Free2 蓝牙耳机',
            secondTitle: '低延迟双传 | 个性化降噪',
            thirdTitle: '',
            url: img32027,
            jsonUrl: '',
            video: '',
            seq: 700,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1843,
            goodsSpuName: 'OPPO Enco Free2',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '599',
              marketPrice: '',
              buyPrice: '489',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 489,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/4522.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满49减10'
              },
              {
                type: 5,
                activityInfo: '积分抵50%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 19,
            goodsCategoryName: '蓝牙耳机（核心品）',
            skuName: 'OPPO Enco Free2 星河白',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '32029',
            skuId: 22610,
            title: 'OPPO Enco M32 无线耳机',
            secondTitle: '充电10分钟 | 听歌20小时',
            thirdTitle: '',
            url: img32029,
            jsonUrl: '',
            video: '',
            seq: 600,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 21349,
            goodsSpuName: 'OPPO Enco M32 无线耳机',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '199',
              marketPrice: '',
              buyPrice: null,
              prefix: '',
              suffix: '',
              currencyTag: '￥'
            },
            price: 199,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/22610.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 5,
                activityInfo: '积分抵10%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 4,
            goodsCategoryName: '有线耳机（新分类）',
            skuName: 'OPPO Enco M32 无线耳机 酷黑',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          }
        ],
        link: 'https://www.opposhop.cn/cn/web/products/8412.html'
      },
      {
        id: 25214,
        picStr: img25214_1,
        title: '智能穿戴',
        url: img25214_2,
        moduleCode: '701102',
        productDetailss: [
          {
            id: '41012',
            skuId: 8384,
            title: 'OPPO Watch 3 系列',
            secondTitle: '旗舰双芯片',
            thirdTitle: '',
            url: img41012,
            jsonUrl: '',
            video: '',
            seq: 1200,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6795,
            goodsSpuName: 'OPPO Watch 3 系列全智能手表',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1999',
              marketPrice: '',
              buyPrice: '1989',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1989,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/8384.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '12期免息'
              },
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵50元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch 3 系列全智能手表 Watch 3 Pro 铂黑 氟橡胶表带款',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '32039',
            skuId: 8885,
            title: 'OPPO Watch SE 全智能手表 薄雾紫',
            secondTitle: '多彩表盘',
            thirdTitle: '',
            url: img32039,
            jsonUrl: '',
            video: '',
            seq: 1190,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6995,
            goodsSpuName: 'OPPO Watch SE 全智能手表',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '999',
              marketPrice: '',
              buyPrice: '989',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 989,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/8885.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '6期免息'
              },
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵50元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch SE 全智能手表 薄雾紫',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41013',
            skuId: 8391,
            title: 'OPPO 手环 2 系列新品手环',
            secondTitle: '全屏 全面升级',
            thirdTitle: '',
            url: img41013,
            jsonUrl: '',
            video: '',
            seq: 1190,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6798,
            goodsSpuName: 'OPPO 手环 2',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '299',
              marketPrice: '',
              buyPrice: '279',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 279,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/8384.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵10%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO 手环 2 NFC 版 晴云蓝',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '32041',
            skuId: 20417,
            title: 'OPPO Watch 2  蓝牙版',
            secondTitle: '双擎长续航',
            thirdTitle: '',
            url: img32041,
            jsonUrl: '',
            video: '',
            seq: 1100,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 20192,
            goodsSpuName: 'OPPO Watch 2 ',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1299',
              marketPrice: '',
              buyPrice: '889',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 889,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/20417.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵100元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch 2 智能手表 铂黑 42mm 蓝牙版',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14742',
            skuId: 20329,
            title: 'OPPO Watch 2 42mm eSIM 版',
            secondTitle: '双擎长续航',
            thirdTitle: '',
            url: img14742,
            jsonUrl: '',
            video: '',
            seq: 900,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 20192,
            goodsSpuName: 'OPPO Watch 2 ',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1499',
              marketPrice: '',
              buyPrice: '989',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 989,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/20329.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵100元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch 2 智能手表 铂黑 42mm eSIM 版',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14744',
            skuId: 20418,
            title: 'OPPO Watch 2  46mm eSIM 版',
            secondTitle: '双擎长续航',
            thirdTitle: '',
            url: img14744,
            jsonUrl: '',
            video: '',
            seq: 700,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 20192,
            goodsSpuName: 'OPPO Watch 2 ',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1999',
              marketPrice: '',
              buyPrice: '1389',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1389,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/20418.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵100元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch 2 智能手表 铂黑 46mm eSIM 版',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '32043',
            skuId: 21160,
            title: 'OPPO Watch Free',
            secondTitle: '全场景睡眠监测',
            thirdTitle: '',
            url: img32043,
            jsonUrl: '',
            video: '',
            seq: 660,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 20643,
            goodsSpuName: 'OPPO Watch Free 手表',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '599',
              marketPrice: '',
              buyPrice: '289',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 289,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/21160.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵30%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch Free 手表 NFC版 静夜黑',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '31743',
            skuId: 21290,
            title: 'OPPO Watch 2 ECG 版',
            secondTitle: '双擎长续航',
            thirdTitle: '',
            url: img31743,
            jsonUrl: '',
            video: '',
            seq: 650,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 20192,
            goodsSpuName: 'OPPO Watch 2 ',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '2499',
              marketPrice: '',
              buyPrice: '1489',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1489,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/21290.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵200元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch 2 智能手表 皓银 ECG 版',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41756',
            skuId: 1392,
            title: 'OPPO Watch 1 手表 46mm 琉金',
            secondTitle: 'eSIM独立通信|运动健康伴侣',
            thirdTitle: '',
            url: img41756,
            jsonUrl: '',
            video: '',
            seq: 610,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 547,
            goodsSpuName: 'OPPO Watch 1系列 手表',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1999',
              marketPrice: '',
              buyPrice: '989',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 989,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/m/product/index?skuId=1392',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵30%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch 1 手表 46mm 琉金',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14743',
            skuId: 4075,
            title: 'OPPO 手环 活力版 蓝色风暴',
            secondTitle: '微信支付宝双支付',
            thirdTitle: '',
            url: img14743,
            jsonUrl: '',
            video: '',
            seq: 600,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1660,
            goodsSpuName: 'OPPO 手环 活力版',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '199',
              marketPrice: '',
              buyPrice: '159',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 159,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/4075.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵30%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO 手环 活力版 蓝色风暴',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41757',
            skuId: 1392,
            title: 'OPPO Watch 1 手表 46mm 琉金',
            secondTitle: 'eSIM独立通信|运动健康伴侣',
            thirdTitle: '',
            url: img41757,
            jsonUrl: '',
            video: '',
            seq: 20,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 547,
            goodsSpuName: 'OPPO Watch 1系列 手表',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1999',
              marketPrice: '',
              buyPrice: '989',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 989,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/m/product/index?skuId=1392',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 2,
                activityInfo: '赠'
              },
              {
                type: 3,
                activityInfo: '满99减10'
              },
              {
                type: 5,
                activityInfo: '积分抵30%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 27,
            goodsCategoryName: '智能穿戴（核心品）',
            skuName: 'OPPO Watch 1 手表 46mm 琉金',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          }
        ],
        link: 'https://www.opposhop.cn/cn/web/products/8384.html'
      },
      {
        id: 2526,
        picStr: img2526_1,
        title: '平板电脑',
        url: img2526_2,
        moduleCode: '701105',
        productDetailss: [
          {
            id: '41938',
            skuId: 22863,
            title: 'OPPO Pad  6GB+128GB 极光紫',
            secondTitle: '骁龙 870 处理器',
            thirdTitle: '',
            url: img41938,
            jsonUrl: '',
            video: '',
            seq: 100,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 21449,
            goodsSpuName: 'OPPO Pad ',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '2299',
              marketPrice: '',
              buyPrice: '2089',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 2089,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/22863.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              },
              {
                type: 5,
                activityInfo: '积分抵50元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25030,
            goodsCategoryName: 'OPPO平板（核心品）',
            skuName: 'OPPO Pad  6GB+128GB 极光紫',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41939',
            skuId: 8360,
            title: 'OPPO Pad  8GB+128GB 耀夜黑',
            secondTitle: '骁龙 870 处理器',
            thirdTitle: '',
            url: img41939,
            jsonUrl: '',
            video: '',
            seq: 99,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 21449,
            goodsSpuName: 'OPPO Pad ',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '2499',
              marketPrice: '',
              buyPrice: '2289',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 2289,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/8360.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              },
              {
                type: 5,
                activityInfo: '积分抵50元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25030,
            goodsCategoryName: 'OPPO平板（核心品）',
            skuName: 'OPPO Pad  8GB+128GB 耀夜黑',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41940',
            skuId: 7208,
            title: 'OPPO Pad Air 4GB+64GB 雾灰',
            secondTitle: '儿童教育助手',
            thirdTitle: '',
            url: img41940,
            jsonUrl: '',
            video: '',
            seq: 98,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 6362,
            goodsSpuName: 'OPPO Pad Air',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1299',
              marketPrice: '',
              buyPrice: '1089',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1089,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/7208.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              },
              {
                type: 5,
                activityInfo: '积分抵30元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25030,
            goodsCategoryName: 'OPPO平板（核心品）',
            skuName: 'OPPO Pad Air 4GB+64GB 雾灰',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41941',
            skuId: 7216,
            title: 'OPPO Pad Air 4GB+128GB 星银',
            secondTitle: '儿童教育助手',
            thirdTitle: '',
            url: img41941,
            jsonUrl: '',
            video: '',
            seq: 97,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 6362,
            goodsSpuName: 'OPPO Pad Air',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1499',
              marketPrice: '',
              buyPrice: '1289',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1289,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/7216.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              },
              {
                type: 5,
                activityInfo: '积分抵30元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25030,
            goodsCategoryName: 'OPPO平板（核心品）',
            skuName: 'OPPO Pad Air 4GB+128GB 星银',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41942',
            skuId: 22931,
            title: 'OPPO Pencil 自研手写笔 OPPO Pad',
            secondTitle: '仅适用 OPPO Pad',
            thirdTitle: '',
            url: img41942,
            jsonUrl: '',
            video: '',
            seq: 90,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 21482,
            goodsSpuName: 'OPPO Pencil 自研手写笔',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '499',
              marketPrice: '',
              buyPrice: null,
              prefix: '',
              suffix: '',
              currencyTag: '￥'
            },
            price: 499,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/22931.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25034,
            goodsCategoryName: '平板配件',
            skuName: 'OPPO Pencil 自研手写笔 OPPO Pad',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41943',
            skuId: 7696,
            title: 'OPPO 智美生活 智能手写笔 OPPO Pad Air',
            secondTitle: '仅适用 OPPO Pad Air',
            thirdTitle: '',
            url: img41943,
            jsonUrl: '',
            video: '',
            seq: 89,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 6520,
            goodsSpuName: 'OPPO 智美生活 智能手写笔',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '299',
              marketPrice: '',
              buyPrice: null,
              prefix: '',
              suffix: '',
              currencyTag: '￥'
            },
            price: 299,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/7696.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25034,
            goodsCategoryName: '平板配件',
            skuName: 'OPPO 智美生活 智能手写笔 OPPO Pad Air',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41944',
            skuId: 7695,
            title: 'OPPO 智美生活 智能磁吸键盘 仅适用 OPPO Pad Air',
            secondTitle: '',
            thirdTitle: '',
            url: img41944,
            jsonUrl: '',
            video: '',
            seq: 87,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 21481,
            goodsSpuName: 'OPPO 智美生活 智能磁吸键盘',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '349',
              marketPrice: '',
              buyPrice: null,
              prefix: '',
              suffix: '',
              currencyTag: '￥'
            },
            price: 349,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/7695.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25034,
            goodsCategoryName: '平板配件',
            skuName: 'OPPO 智美生活 智能磁吸键盘 仅适用 OPPO Pad Air',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41945',
            skuId: 7869,
            title: 'OPPO 智美生活 智能皮套 白色 仅适用 OPPO Pad Air',
            secondTitle: '智能休眠 | 磁吸支撑',
            thirdTitle: '',
            url: img41945,
            jsonUrl: '',
            video: '',
            seq: 85,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 21483,
            goodsSpuName: 'OPPO 智美生活 智能皮套',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '99',
              marketPrice: '',
              buyPrice: null,
              prefix: '',
              suffix: '',
              currencyTag: '￥'
            },
            price: 99,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/7869.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25034,
            goodsCategoryName: '平板配件',
            skuName: 'OPPO 智美生活 智能皮套 白色 仅适用 OPPO Pad Air',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41946',
            skuId: 7916,
            title: 'OPPO 智美生活 平板钢化膜 高清 仅适用 OPPO Pad',
            secondTitle: '仅适用 OPPO Pad',
            thirdTitle: '',
            url: img41946,
            jsonUrl: '',
            video: '',
            seq: 84,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 21484,
            goodsSpuName: 'OPPO 智美生活 平板钢化膜',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '79',
              marketPrice: '',
              buyPrice: null,
              prefix: '',
              suffix: '',
              currencyTag: '￥'
            },
            price: 79,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/7916.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '',
            priceSuffix: null,
            goodsTopCategoryId: 2,
            goodsTopCategoryName: '配件',
            goodsCategoryId: 25034,
            goodsCategoryName: '平板配件',
            skuName: 'OPPO 智美生活 平板钢化膜 高清 仅适用 OPPO Pad',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          }
        ],
        link: 'https://www.opposhop.cn/cn/web/products/22863.html'
      },
      {
        id: 2527,
        picStr: img2527_1,
        title: '智能电视',
        url: img2527_2,
        moduleCode: '701103',
        productDetailss: [
          {
            id: '41977',
            skuId: 6835,
            title: 'OPPO 智能电视 K9x 65英寸',
            secondTitle: '开机无广告',
            thirdTitle: '',
            url: img41977,
            jsonUrl: '',
            video: '',
            seq: 10000,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 6237,
            goodsSpuName: 'OPPO 智能电视 K9x',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '2499',
              marketPrice: '',
              buyPrice: '1989',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1989,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/6835.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 70,
            goodsCategoryName: '智能电视机',
            skuName: 'OPPO 智能电视 K9x 65英寸',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41978',
            skuId: 6836,
            title: 'OPPO 智能电视 K9x 50英寸',
            secondTitle: '开机无广告',
            thirdTitle: '',
            url: img41978,
            jsonUrl: '',
            video: '',
            seq: 9000,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 6237,
            goodsSpuName: 'OPPO 智能电视 K9x',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1399',
              marketPrice: '',
              buyPrice: '1289',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1289,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/6836.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 70,
            goodsCategoryName: '智能电视机',
            skuName: 'OPPO 智能电视 K9x 50英寸',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41979',
            skuId: 6837,
            title: 'OPPO 智能电视 K9x 43英寸',
            secondTitle: '开机无广告',
            thirdTitle: '',
            url: img41979,
            jsonUrl: '',
            video: '',
            seq: 8000,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 6237,
            goodsSpuName: 'OPPO 智能电视 K9x',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '1199',
              marketPrice: '',
              buyPrice: '989',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 989,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/6837.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 70,
            goodsCategoryName: '智能电视机',
            skuName: 'OPPO 智能电视 K9x 43英寸',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41980',
            skuId: 21300,
            title: 'OPPO 智能电视 K9 75英寸',
            secondTitle: '4K全金属巨幕',
            thirdTitle: '',
            url: img41980,
            jsonUrl: '',
            video: '',
            seq: 7000,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 1911,
            goodsSpuName: 'OPPO 智能电视 K9',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '5799',
              marketPrice: '',
              buyPrice: '3689',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 3689,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/21300.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 70,
            goodsCategoryName: '智能电视机',
            skuName: 'OPPO 智能电视 K9 75英寸',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41981',
            skuId: 4711,
            title: 'OPPO 智能电视 K9 65英寸',
            secondTitle: 'OPPO 蓝光团队调校',
            thirdTitle: '',
            url: img41981,
            jsonUrl: '',
            video: '',
            seq: 6000,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 1911,
            goodsSpuName: 'OPPO 智能电视 K9',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '3499',
              marketPrice: '',
              buyPrice: '2289',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 2289,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/4711.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 70,
            goodsCategoryName: '智能电视机',
            skuName: 'OPPO 智能电视 K9 65英寸',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41982',
            skuId: 4710,
            title: 'OPPO 智能电视 K9 55英寸',
            secondTitle: '小布语音助手',
            thirdTitle: '',
            url: img41982,
            jsonUrl: '',
            video: '',
            seq: 5900,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 1911,
            goodsSpuName: 'OPPO 智能电视 K9',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '2299',
              marketPrice: '',
              buyPrice: '1489',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1489,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/4710.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 70,
            goodsCategoryName: '智能电视机',
            skuName: 'OPPO 智能电视 K9 55英寸',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41983',
            skuId: 2226,
            title: 'OPPO 智能电视 R1 55英寸',
            secondTitle: '',
            thirdTitle: '',
            url: img41983,
            jsonUrl: '',
            video: '',
            seq: 95,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 972,
            goodsSpuName: 'OPPO 智能电视 R1',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '4299',
              marketPrice: '',
              buyPrice: null,
              prefix: '',
              suffix: '',
              currencyTag: '￥'
            },
            price: 4299,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/2226.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 70,
            goodsCategoryName: '智能电视机',
            skuName: 'OPPO 智能电视 R1 55英寸',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41984',
            skuId: 21543,
            title: 'OPPO 智能电视 S1 65英寸',
            secondTitle: '',
            thirdTitle: '',
            url: img41984,
            jsonUrl: '',
            video: '',
            seq: 94,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 20800,
            goodsSpuName: 'OPPO 智能电视 S1',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '7999',
              marketPrice: '',
              buyPrice: '6489',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 6489,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/21543.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满999减10'
              }
            ],
            placeholderLabel: {
              type: 20,
              activityInfo: '缺货'
            },
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 70,
            goodsCategoryName: '智能电视机',
            skuName: 'OPPO 智能电视 S1 65英寸',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41985',
            skuId: 21540,
            title: 'OPPO 蓝牙语音遥控器 黑色',
            secondTitle: '',
            thirdTitle: '',
            url: img41985,
            jsonUrl: '',
            video: '',
            seq: 93,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 0,
            goodsSpuId: 20798,
            goodsSpuName: 'OPPO 蓝牙语音遥控器',
            isShowIcon: 0,
            topIcon: '',
            cardType: 0,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '99',
              marketPrice: '',
              buyPrice: null,
              prefix: '',
              suffix: '',
              currencyTag: '￥'
            },
            price: 99,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/products/21540.html',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '',
            priceSuffix: null,
            goodsTopCategoryId: 69,
            goodsTopCategoryName: 'OPPO 电视',
            goodsCategoryId: 71,
            goodsCategoryName: '电视机配件',
            skuName: 'OPPO 蓝牙语音遥控器 黑色',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          }
        ],
        link: 'https://www.opposhop.cn/cn/web/products/6835.html'
      },
      {
        id: 2528,
        picStr: img2528_1,
        title: '充电配件',
        moduleCode: '',
        productDetailss: [],
        link: ''
      },
      {
        id: 2529,
        picStr: img2529_1,
        title: '数据线',
        moduleCode: '',
        productDetailss: [],
        link: ''
      },
      {
        id: 2530,
        picStr: img2530_1,
        title: '手机壳膜',
        moduleCode: '',
        productDetailss: [],
        link: ''
      }
    ]
  }
}
