import img168100 from '@/assets/images/saveImg/onePlusInfo/168100.webp'
import img168101 from '@/assets/images/saveImg/onePlusInfo/168101.webp'
import img168102 from '@/assets/images/saveImg/onePlusInfo/168102.webp'
import img168103 from '@/assets/images/saveImg/onePlusInfo/168103.webp'
import img1140_1 from '@/assets/images/saveImg/onePlusInfo/1140_1.png'
import img1140_2 from '@/assets/images/saveImg/onePlusInfo/1140_2.jpg'
import img40006 from '@/assets/images/saveImg/onePlusInfo/40006.png'
import img41034 from '@/assets/images/saveImg/onePlusInfo/41034.png'
import img39931 from '@/assets/images/saveImg/onePlusInfo/39931.png'
import img38832 from '@/assets/images/saveImg/onePlusInfo/38832.png'
import img1141_1 from '@/assets/images/saveImg/onePlusInfo/1141_1.png'
import img1141_2 from '@/assets/images/saveImg/onePlusInfo/1141_2.jpg'
import img14610 from '@/assets/images/saveImg/onePlusInfo/14610.png'
import img39990 from '@/assets/images/saveImg/onePlusInfo/39990.png'
import img22971 from '@/assets/images/saveImg/onePlusInfo/22971.png'
import img14611 from '@/assets/images/saveImg/onePlusInfo/14611.png'
import img39991 from '@/assets/images/saveImg/onePlusInfo/39991.png'
import img14612 from '@/assets/images/saveImg/onePlusInfo/14612.png'
import img1142_1 from '@/assets/images/saveImg/onePlusInfo/1142_1.png'
import img1142_2 from '@/assets/images/saveImg/onePlusInfo/1142_2.jpg'
import img1143_1 from '@/assets/images/saveImg/onePlusInfo/1143_1.png'
import img1143_2 from '@/assets/images/saveImg/onePlusInfo/1143_2.webp'
import img14648 from '@/assets/images/saveImg/onePlusInfo/14648.png'
import img14649 from '@/assets/images/saveImg/onePlusInfo/14649.png'
import img14650 from '@/assets/images/saveImg/onePlusInfo/14650.png'
import img1144_1 from '@/assets/images/saveImg/onePlusInfo/1144_1.png'
import img1144_2 from '@/assets/images/saveImg/onePlusInfo/1144_2.jpg'
import img29908 from '@/assets/images/saveImg/onePlusInfo/29908.png'
import img30696 from '@/assets/images/saveImg/onePlusInfo/30696.png'
import img22974 from '@/assets/images/saveImg/onePlusInfo/22974.png'

// http://codercba.com:9060/oppo-nuxt/api/home/info?type=onePlus
export default {
  code: 200,
  data: {
    navbars: [
      {
        id: '1276',
        title: 'OPPO专区',
        type: 'oppo',
        showName: 0,
        url: '',
        jsonUrl: '',
        clickUrl: '',
        jsonClickUrl: '',
        beginAt: null,
        endAt: null,
        seq: 100,
        labelDetailss: [],
        link: 'https://www.opposhop.cn/cn/web/topic/700100.html',
        isLogin: 0,
        moduleCode: '700002',
        rows: 0,
        cols: 0,
        maxProductNum: 0
      },
      {
        id: '1277',
        title: 'OnePlus专区',
        type: 'onePlus',
        showName: 0,
        url: '',
        jsonUrl: '',
        clickUrl: '',
        jsonClickUrl: '',
        beginAt: null,
        endAt: null,
        seq: 90,
        labelDetailss: [],
        link: 'https://www.opposhop.cn/cn/web/topic/700200.html',
        isLogin: 0,
        moduleCode: '700002',
        rows: 0,
        cols: 0,
        maxProductNum: 0
      },
      {
        id: '1280',
        title: '智能硬件',
        type: 'intelligent',
        showName: 0,
        url: '',
        jsonUrl: '',
        clickUrl: '',
        jsonClickUrl: '',
        beginAt: null,
        endAt: null,
        seq: 75,
        labelDetailss: [],
        link: 'https://www.opposhop.cn/cn/web/topic/700400.html',
        isLogin: 0,
        moduleCode: '700002',
        rows: 0,
        cols: 0,
        maxProductNum: 0
      },
      {
        id: '1281',
        title: '服务',
        type: 'server',
        showName: 0,
        url: '',
        jsonUrl: '',
        clickUrl: '',
        jsonClickUrl: '',
        beginAt: null,
        endAt: null,
        seq: 50,
        labelDetailss: [],
        link: 'https://support.oppo.com/cn/',
        isLogin: 0,
        moduleCode: '700002',
        rows: 0,
        cols: 0,
        maxProductNum: 0
      }
    ],
    banners: [
      {
        id: 168100,
        picStr: img168100,
        link: 'https://www.opposhop.cn/cn/web/products/8289.html?us=pc&um=onepluschannel&uc=banner'
      },
      {
        id: 168101,
        picStr: img168101,
        link: 'https://www.opposhop.cn/cn/web/products/6746.html?us=pc&um=onepluschannel&uc=banner'
      },
      {
        id: 168102,
        picStr: img168102,
        link: 'https://www.opposhop.cn/cn/web/products/22926.html?us=pc&um=onepluschannel&uc=banner'
      },
      {
        id: 168103,
        picStr: img168103,
        link: 'https://www.opposhop.cn/cn/web/products/7258.html?us=pc&um=onepluschannel&uc=banner'
      }
    ],
    categorys: [
      {
        id: 1140,
        picStr: img1140_1,
        title: '一加手机',
        url: img1140_2,
        moduleCode: '700901',
        productDetailss: [
          {
            id: '40006',
            skuId: 8289,
            title: '一加 Ace Pro 12GB+256GB 黑森 官方标配',
            secondTitle: '性能手机新标杆',
            thirdTitle: '',
            url: img40006,
            jsonUrl: '',
            video: '',
            seq: 1200,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6769,
            goodsSpuName: '一加 Ace Pro',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '3499',
              marketPrice: '',
              buyPrice: '3489',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 3489,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/8289.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '12期免息'
              },
              {
                type: 3,
                activityInfo: '满2000减10'
              },
              {
                type: 5,
                activityInfo: '积分抵100元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 45,
            goodsTopCategoryName: 'OnePlus手机',
            goodsCategoryId: 6015,
            goodsCategoryName: '一加Ace系列',
            skuName: '一加 Ace Pro 12GB+256GB 黑森 官方标配',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '41034',
            skuId: 6746,
            title: '一加 Ace 12GB+256GB 开黑 官方标配',
            secondTitle: '王牌登场 快稳狠',
            thirdTitle: '',
            url: img41034,
            jsonUrl: '',
            video: '',
            seq: 1150,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6200,
            goodsSpuName: '一加 Ace',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '2999',
              marketPrice: '',
              buyPrice: '2589',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 2589,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/6746.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '6期免息'
              },
              {
                type: 3,
                activityInfo: '满2000减10'
              },
              {
                type: 5,
                activityInfo: '积分抵100元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 45,
            goodsTopCategoryName: 'OnePlus手机',
            goodsCategoryId: 6015,
            goodsCategoryName: '一加Ace系列',
            skuName: '一加 Ace 12GB+256GB 开黑 官方标配',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '39931',
            skuId: 7258,
            title: '一加 Ace 竞速版 8GB+256GB 光速蓝 官方标配',
            secondTitle: '高能竞速 满血出击',
            thirdTitle: '',
            url: img39931,
            jsonUrl: '',
            video: '',
            seq: 1105,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6368,
            goodsSpuName: '一加 Ace 竞速版',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '2199',
              marketPrice: '',
              buyPrice: '1899',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 1899,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/7258.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 3,
                activityInfo: '满2000减10'
              },
              {
                type: 5,
                activityInfo: '积分抵100元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 45,
            goodsTopCategoryName: 'OnePlus手机',
            goodsCategoryId: 6015,
            goodsCategoryName: '一加Ace系列',
            skuName: '一加 Ace 竞速版 8GB+256GB 光速蓝 官方标配',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '38832',
            skuId: 22926,
            title: '一加 10 Pro 12GB+512GB 胖达白 官方标配',
            secondTitle: '第十代性能旗舰',
            thirdTitle: '',
            url: img38832,
            jsonUrl: '',
            video: '',
            seq: 1100,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 21344,
            goodsSpuName: '一加 10 Pro',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '5299',
              marketPrice: '',
              buyPrice: '4489',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 4489,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/22926.html?us=pc&um=shouye&uc=10pro&ut=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '12期免息'
              },
              {
                type: 3,
                activityInfo: '满2000减10'
              },
              {
                type: 5,
                activityInfo: '积分抵200元'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 45,
            goodsTopCategoryName: 'OnePlus手机',
            goodsCategoryId: 25026,
            goodsCategoryName: '一加10系列',
            skuName: '一加 10 Pro 12GB+512GB 胖达白 官方标配',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          }
        ]
      },
      {
        id: 1141,
        picStr: img1141_1,
        title: '一加耳机',
        url: img1141_2,
        moduleCode: '700902',
        productDetailss: [
          {
            id: '14610',
            skuId: 6776,
            title: '一加 Buds N 月光白',
            secondTitle: '',
            thirdTitle: '',
            url: img14610,
            jsonUrl: '',
            video: '',
            seq: 3000,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6215,
            goodsSpuName: '一加 Buds N 真无线蓝牙耳机',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '199',
              marketPrice: '',
              buyPrice: '149',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 149,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/6776.htmly?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 5,
                activityInfo: '积分抵5%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 53,
            goodsCategoryName: 'OnePlus耳机',
            skuName: '一加 Buds N 真无线蓝牙耳机 月光白',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '39990',
            skuId: 6777,
            title: '一加 Buds N 暮影黑',
            secondTitle: '',
            thirdTitle: '',
            url: img39990,
            jsonUrl: '',
            video: '',
            seq: 2000,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6215,
            goodsSpuName: '一加 Buds N 真无线蓝牙耳机',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '199',
              marketPrice: '',
              buyPrice: '149',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 149,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/6777.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 5,
                activityInfo: '积分抵5%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 53,
            goodsCategoryName: 'OnePlus耳机',
            skuName: '一加 Buds N 真无线蓝牙耳机 暮影黑',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '22971',
            skuId: 22714,
            title: '一加 Buds Pro 秘银',
            secondTitle: '40dB 智能主动降噪',
            thirdTitle: '',
            url: img22971,
            jsonUrl: '',
            video: '',
            seq: 700,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 20316,
            goodsSpuName: '一加 Buds Pro 降噪耳机',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '799',
              marketPrice: '',
              buyPrice: '589',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 589,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/22714.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '6期免息'
              },
              {
                type: 3,
                activityInfo: '满49减10'
              },
              {
                type: 5,
                activityInfo: '积分抵10%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 53,
            goodsCategoryName: 'OnePlus耳机',
            skuName: '一加 Buds Pro 降噪耳机 秘银',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14611',
            skuId: 20557,
            title: 'OnePlus Buds Pro',
            secondTitle: '40dB 智能主动降噪',
            thirdTitle: '',
            url: img14611,
            jsonUrl: '',
            video: '',
            seq: 600,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 20316,
            goodsSpuName: '一加 Buds Pro 降噪耳机',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '799',
              marketPrice: '',
              buyPrice: '589',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 589,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/20557.htmly?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '6期免息'
              },
              {
                type: 3,
                activityInfo: '满49减10'
              },
              {
                type: 5,
                activityInfo: '积分抵10%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 53,
            goodsCategoryName: 'OnePlus耳机',
            skuName: '一加 Buds Pro 降噪耳机 独白',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '39991',
            skuId: 6779,
            title: '一加云耳 Z2 蓝调',
            secondTitle: '',
            thirdTitle: '',
            url: img39991,
            jsonUrl: '',
            video: '',
            seq: 500,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6216,
            goodsSpuName: '一加云耳 Z2 颈挂无线耳机',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '199',
              marketPrice: '',
              buyPrice: '149',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 149,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/6779.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 5,
                activityInfo: '积分抵5%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 53,
            goodsCategoryName: 'OnePlus耳机',
            skuName: '一加云耳 Z2 颈挂无线耳机 蓝调',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14612',
            skuId: 6009,
            title: '一加 Buds Z2 新品耳机',
            secondTitle: '40dB 主动降噪',
            thirdTitle: '',
            url: img14612,
            jsonUrl: '',
            video: '',
            seq: 500,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 6005,
            goodsSpuName: '一加 Buds Z2 降噪耳机',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '499',
              marketPrice: '',
              buyPrice: '289',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 289,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/6009.htmly?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 1,
                activityInfo: '3期免息'
              },
              {
                type: 3,
                activityInfo: '满49减10'
              },
              {
                type: 5,
                activityInfo: '积分抵20%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 53,
            goodsCategoryName: 'OnePlus耳机',
            skuName: '一加 Buds Z2 降噪耳机 昼白',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          }
        ],
        link: 'https://www.opposhop.cn/cn/web/products/6776.html?us=pc&um=shouye&uc=onepluschannel'
      },
      {
        id: 1142,
        picStr: img1142_1,
        title: '一加保护膜',
        url: img1142_2,
        moduleCode: '700904',
        productDetailss: [],
        link: ''
      },
      {
        id: 1143,
        picStr: img1143_1,
        title: '一加保护壳',
        url: img1143_2,
        moduleCode: '700904',
        productDetailss: [
          {
            id: '14648',
            skuId: 4005,
            title: '一加 Ace 全保护壳 砂岩黑',
            secondTitle: '',
            thirdTitle: '',
            url: img14648,
            jsonUrl: '',
            video: '',
            seq: 700,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1636,
            goodsSpuName: '一加 Ace 全保护壳',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '139',
              marketPrice: '',
              buyPrice: '39',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 49,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/4005.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: {
              type: 20,
              activityInfo: '缺货'
            },
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 51,
            goodsCategoryName: 'OnePlus 手机壳',
            skuName: '一加 Ace 全保护壳 砂岩黑',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14649',
            skuId: 4005,
            title: '一加 9RT 全保护壳',
            secondTitle: '',
            thirdTitle: '',
            url: img14649,
            jsonUrl: '',
            video: '',
            seq: 700,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1636,
            goodsSpuName: '一加 9RT 全保护壳',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '139',
              marketPrice: '',
              buyPrice: '39',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 49,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/4005.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: {
              type: 20,
              activityInfo: '缺货'
            },
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 51,
            goodsCategoryName: 'OnePlus 手机壳',
            skuName: '一加 9RT 全保护壳 砂岩黑',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '14650',
            skuId: 4005,
            title: 'OnePlus 9R 保护壳 磁感电路',
            secondTitle: '',
            thirdTitle: '',
            url: img14650,
            jsonUrl: '',
            video: '',
            seq: 700,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1636,
            goodsSpuName: '一加 9R 保护壳',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '149',
              marketPrice: '',
              buyPrice: '49',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 49,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/4005.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [],
            placeholderLabel: {
              type: 20,
              activityInfo: '缺货'
            },
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 51,
            goodsCategoryName: 'OnePlus 手机壳',
            skuName: '一加 9R 保护壳 磁感电路',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          }
        ],
        link: ''
      },
      {
        id: 1144,
        picStr: img1144_1,
        title: '一加充电装备',
        url: img1144_2,
        productDetailss: [
          {
            id: '29908',
            skuId: 3752,
            title: '一加 Warp 50 无线超级闪充充电器',
            secondTitle: '',
            thirdTitle: '',
            url: img29908,
            jsonUrl: '',
            video: '',
            seq: 1500,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1540,
            goodsSpuName: '一加 Warp 50 无线超级闪充充电器',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '329',
              marketPrice: '',
              buyPrice: '299',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 299,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/3752.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 5,
                activityInfo: '积分抵30%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 52,
            goodsCategoryName: 'OnePlus 充电器',
            skuName: '一加 Warp 50 无线超级闪充充电器 50W',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '30696',
            skuId: 2515,
            title: '一加 Warp 闪充 65W 电源适配器 中规',
            secondTitle: '',
            thirdTitle: '',
            url: img30696,
            jsonUrl: '',
            video: '',
            seq: 1400,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1074,
            goodsSpuName: '一加 Warp 闪充 电源适配器 中规',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '149',
              marketPrice: '',
              buyPrice: '129',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 129,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/2515.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 5,
                activityInfo: '积分抵30%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 52,
            goodsCategoryName: 'OnePlus 充电器',
            skuName: '一加 Warp 闪充 电源适配器 中规 65W',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          },
          {
            id: '22974',
            skuId: 2516,
            title: '一加 Warp 闪充 双Type-C 数据线 100cm',
            secondTitle: '',
            thirdTitle: '',
            url: img22974,
            jsonUrl: '',
            video: '',
            seq: 1300,
            configKeyLattice: 0,
            latticeIndex: 0,
            configProductType: 601,
            goodsSpuId: 1075,
            goodsSpuName: '一加 Warp 闪充 Type-C 转 Type-C 数据线',
            isShowIcon: 0,
            topIcon: '',
            cardType: 1,
            backColor: '',
            liveInfoJson: null,
            businessInfoJson: null,
            priceInfo: {
              originalPrice: '',
              price: '79',
              marketPrice: '',
              buyPrice: '69',
              prefix: '到手价',
              suffix: '',
              currencyTag: '￥'
            },
            price: 69,
            originalPrice: null,
            categoryId: 2,
            link: 'https://www.opposhop.cn/cn/web/products/2516.html?us=pc&um=shouye&uc=onepluschannel',
            isLogin: 0,
            marketPrice: '',
            nameLabel: null,
            imageLabel: null,
            extendList: null,
            heytapInfo: null,
            activityList: [
              {
                type: 5,
                activityInfo: '积分抵30%'
              }
            ],
            placeholderLabel: null,
            vipDiscounts: null,
            nameLabelWidth: null,
            nameLabelHeight: null,
            pricePrefix: '到手价',
            priceSuffix: null,
            goodsTopCategoryId: 46,
            goodsTopCategoryName: 'OnePlus配件',
            goodsCategoryId: 52,
            goodsCategoryName: 'OnePlus 充电器',
            skuName: '一加 Warp 闪充 Type-C 转 Type-C 数据线 100cm',
            cardInfoType: null,
            liveUrl: null,
            storage: null,
            seckill: null,
            rankInfo: null,
            businessLink: '',
            sellPoints: null,
            commentCount: null,
            commentRate: null,
            interenve: false,
            productDetailLabelss: []
          }
        ],
        link: ''
      }
    ]
  }
}
